version: "3.8"
services:
  app:
    build: .
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - db
  db:
    image: "mysql:5.7"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: agileSoftware
      MYSQL_DATABASE: agileSoftware
      MYSQL_USER: agileSoftware
      MYSQL_PASSWORD: agileSoftware
